[phases.install_api]
directory = "api"
cmds = ["npm install"]

[phases.build_ui]
directory = "ui"
cmds = ["npm install", "npx vite build"]

[phases.start_api]
directory = "api"
cmds = ["npm start"]

[phases.start_ui]
directory = "ui"
cmds = ["npm start"]
