[[env]]
key = "NODE_ENV"
value = "production"

[[service]]
name = "api"
path = "api"
build = "npm install"  # This will install dependencies for the API
start = "npm start"     # This will start the API in production mode

[[service]]
name = "ui"
path = "ui"
build = "npm install && npm run build"  # Install and build the UI
start = "npm start"  # This will start the UI server
