[[service]]
name = "api"
path = "api"
build = "npm install"  # Install dependencies
start = "npm start"    # Start the API

[[service]]
name = "ui"
path = "ui"
build = "npm install"  # Install dependencies
start = "npm run build"  # Change this to whatever starts your UI
